GET http://172.10.8.174:3001/
Content-Type: application/json

###

POST http://172.10.7.60:3001/api/auth/signIn
Content-Type: application/json

{
  "id": "asdf",
  "nickname": "asdf",
  "profileURL": "asdf"
}

###
# 모든 건물들 불러오기

GET http://172.10.7.60:3001/api/building/buildingList HTTP/1.1

###
# 즐겨찾는 장소 불러오기

GET http://172.10.7.60:3001/api/search/favorite?user_id=asdf HTTP/1.1

###
# 즐겨찾는 장소 추가하기

POST http://172.10.7.60:3001/api/search/postFavorite HTTP/1.1
Content-Type: application/json

{
  "user_id": "asdf",
  "building_id": "4de6d2c8-d7c0-11ef-8650-fa163e2f32e9",
  "favorite_name": "home"
}

###
# 최근 검색 장소 불러오기 (최근 검색부터)

GET http://172.10.7.60:3001/api/search/recentBuilding?user_id=asdf HTTP/1.1

###
# 최근 검색 장소 추가하기 

POST http://172.10.7.60:3001/api/search/postRecentBuilding HTTP/1.1
Content-Type: application/json

{
  "user_id": "asdf",
  "building_id": "4de6d2c8-d7c0-11ef-8650-fa163e2f32e9"
}

###
# 최근 검색 경로 불러오기 (최근 검색부터)

GET http://172.10.7.60:3001/api/search/recentFlight?user_id=asdf HTTP/1.1

###
# 경로 검색

POST http://172.10.7.60:3001/api/path/single HTTP/1.1
Content-Type: application/json

{
  "user_id": "asdf",
  "originID": "4de6e1c4-d7c0-11ef-8650-fa163e2f32e9",
  "destinationID": "4de6e6fa-d7c0-11ef-8650-fa163e2f32e9"
}

###

GET http://172.10.7.60:3001/api/show/randomFlight HTTP/1.1

###

GET http://172.10.7.60:3001/api/show/flight?user_id=asdf&originID=4de6dddf-d7c0-11ef-8650-fa163e2f32e9&destinationID=4de6d2c8-d7c0-11ef-8650-fa163e2f32e9 HTTP/1.1

###

GET /ws?user_id=asdf HTTP/1.1
Host: 172.10.7.60:3001/api/auth/signIn
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==
Sec-WebSocket-Version: 13
