GET http://172.10.7.60:3001/
Content-Type: application/json

###

POST http://172.10.7.60:3001/api/auth/signIn
Content-Type: application/json

{
  "id": "asdf",
  "nickname": "asdf",
  "profileURL": "asdf"
}

###

GET /ws?user_id=asdf HTTP/1.1
Host: 172.10.7.60:3001/api/auth/signIn
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==
Sec-WebSocket-Version: 13
