GET http://172.10.7.60:3001/
Content-Type: application/json

###

POST http://172.10.7.60:3001/api/auth/signIn
Content-Type: application/json

{
  "id": "asdf",
  "nickname": "asdf",
  "profileURL": "asdf"
}

###
# 즐겨찾는 장소 불러오기

GET http://172.10.7.60:3001/api/search/favorite?user_id=asdf HTTP/1.1

###
# 최근 검색 장소 불러오기

GET http://172.10.7.60:3001/api/search/recentBuilding?user_id=asdf HTTP/1.1

###
# 경로 검색

POST http://172.10.7.60:3001/api/path/single HTTP/1.1
Content-Type: application/json

{
  "user_id": "asdf",
  "start": {
    "latitude": 37.5662952,
    "longitude": 126.9779451
  },
  "end": {
    "latitude": 37.5662952,
    "longitude": 126.9779451
  }
}

###

GET /ws?user_id=asdf HTTP/1.1
Host: 172.10.7.60:3001/api/auth/signIn
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==
Sec-WebSocket-Version: 13
